all_areas <- c(
    "Aberdeen"   ,
    "Orkney"           ,
    "Fife"        ,
    "Glasgow"      ,
    "East Dunbartonshire" ,
    "East Renfrewshire"    ,
    "North Ayrshire"   ,
    "Stirling"    ,
    "Dumfries and Galloway",
    "Angus"          ,
    "Shetland"        ,
    "South Ayrshire"    ,
    "South Lanarkshire"  ,
    "Falkirk"        ,
    "West Lothian"  ,
    "Dundee City"      ,
    "Perth and Kinross"  ,
    "North Lanarkshire"   ,
    "Highland"     ,
    "Edinburgh"    ,
    "Aberdeenshire"  ,
    "East Lothian"    ,
    "East Ayrshire"  ,
    "Moray"     ,
    "Scottish Borders"  ,
    "Inverclyde"       ,
    "Clackmannanshire"   ,
    "West Dunbartonshire"  ,
    "Midlothian"      ,
    "Renfrewshire"
  ) |> 
  sort()
